name: Flutter CI with secret keys

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Create .env file
      run: |
        echo FIREBASE_OPTIONS_API_KEY=${{ secrets.FIREBASE_OPTIONS_API_KEY }} >> .env
        echo FIREBASE_OPTIONS_APP_ID=${{ secrets.FIREBASE_OPTIONS_APP_ID }} >> .env

    - name: Build Flutter APK
      run: flutter build apk --release

    # Optional: Upload APK artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
